COMP=aii_sindes
NAME=$(COMP)
AUTHOR=Stijn De Weirdt
MAINTAINER=Stijn De Weirdt
DESCRIPTION=AII plug-in that generates Kickstart files.
DESCR=$(DESCRIPTION)
VERSION=0.3.2
RELEASE=1
DATE=24/03/08 17:04
