COMP=disklayout
NAME=ndpf-$(COMP)
AUTHOR=Ronald Starink
MAINTAINER=Ronald Starink
DESCRIPTION=AII plug-in to directly define partitions in Anaconda
DESCR=$(DESCRIPTION)
VERSION=0.1.1
RELEASE=1
DATE=27/07/09 18:31
