COMP=xen_dom0
NAME=ndpf-$(COMP)
AUTHOR=Ronald Starink
MAINTAINER=Ronald Starink
DESCRIPTION=AII plug-in that performs actions before booting into Xen kernel
DESCR=$(DESCRIPTION)
VERSION=0.1.0
RELEASE=1
DATE=02/04/08 12:00
